### PR TITLE
feat: convert to upm packages.

### PR DESCRIPTION
**Pull request by favoyang**
Part of https://github.com/sebas77/Svelto.ECS/issues/45
- add package.json to both `Svelto.ECS` and `Svelto.Services` folders
- set both version string to 2.9.1 to match the `Svelto.Common` package

Know issues
- `Svelto.Services` won't compile, because of missing the TaskContract type. It sounds part of the `Svelto.Tasks`, but I can not find the class name.
    ```
    Svelto.ECS\Svelto.Services\IServiceRequest.cs(8,15): error CS0246: The type or namespace name 'TaskContract' could not be found (are you missing a using directive or an assembly reference?)
    Svelto.ECS\Svelto.Services\Unity\Web\StandardWebRequest.cs(47,28): error CS0246: The type or namespace name 'TaskContract' could not be found (are you missing a using directive or an assembly reference?)
    ```
- `Svelto.Services.asmdef` references Utf8Json, a package from nuget. But I can not find any code in that folder references typical `JsonReader` or `JsonWriter`. This won't generate any errors, but maybe that reference cloud be removed?

image

Notice:
- since the repository contains two packages, turns it into a *monorepo*. So further release need bump version of both package.json files.

### CODE REVIEW

**Comment by sebas77** [comment]
UTF8 Json is a mistake, thanks to spot it out. Can you delete it?

**Comment by sebas77** [comment]
OK I think I will remove Svelto.Services from Svelto.ECS and move to its own repository. You won't need to put Svelto.Services in to UPM. By the way, can you show me how UPM is used inside Unity?

**Comment by favoyang** [comment]
Okay, UTF8J refernece removed, Svelto.Services/package.json removed (you can turn it to package your own in the future).

**Comment by favoyang** [comment]
I will show you how to use upm in the https://github.com/sebas77/Svelto.ECS/issues/45 later. This PR is merge-able now.

**Comment by favoyang** [comment]
Looks good, I will close this one.

**Pull request closed without merging**
